// Date: 26/05/2014 18:08:16
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package it.kimpton.lathe.block.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLargeColumn extends ModelBase
{
  //fields
    ModelRenderer Core;
    ModelRenderer Shape81;
    ModelRenderer Shape82;
    ModelRenderer Shape83;
    ModelRenderer Shape84;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
  
  public ModelLargeColumn()
  {
    textureWidth = 154;
    textureHeight = 154;
    
      Core = new ModelRenderer(this, 33, 0);
      Core.addBox(0F, 0F, 0F, 12, 16, 12);
      Core.setRotationPoint(-6F, 8F, -6F);
      Core.setTextureSize(154, 154);
      Core.mirror = true;
      setRotation(Core, 0F, 0F, 0F);
      Shape81 = new ModelRenderer(this, 0, 0);
      Shape81.addBox(0F, 0F, 0F, 2, 16, 8);
      Shape81.setRotationPoint(-8F, 8F, -4F);
      Shape81.setTextureSize(154, 154);
      Shape81.mirror = true;
      setRotation(Shape81, 0F, 0F, 0F);
      Shape82 = new ModelRenderer(this, 0, 0);
      Shape82.addBox(0F, 0F, 0F, 2, 16, 8);
      Shape82.setRotationPoint(-4F, 8F, -6F);
      Shape82.setTextureSize(154, 154);
      Shape82.mirror = true;
      setRotation(Shape82, 0F, 1.570796F, 0F);
      Shape83 = new ModelRenderer(this, 0, 0);
      Shape83.addBox(0F, 0F, 0F, 2, 16, 8);
      Shape83.setRotationPoint(6F, 8F, -4F);
      Shape83.setTextureSize(154, 154);
      Shape83.mirror = true;
      setRotation(Shape83, 0F, 0F, 0F);
      Shape84 = new ModelRenderer(this, 0, 0);
      Shape84.addBox(0F, 0F, 0F, 2, 16, 8);
      Shape84.setRotationPoint(-4F, 8F, 8F);
      Shape84.setTextureSize(154, 154);
      Shape84.mirror = true;
      setRotation(Shape84, 0F, 1.570796F, 0F);
      Shape11 = new ModelRenderer(this, 0, 0);
      Shape11.addBox(0F, 0F, 0F, 1, 16, 1);
      Shape11.setRotationPoint(-7F, 8F, -5F);
      Shape11.setTextureSize(154, 154);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 0);
      Shape12.addBox(0F, 0F, 0F, 1, 16, 1);
      Shape12.setRotationPoint(-5F, 8F, -7F);
      Shape12.setTextureSize(154, 154);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 0, 0);
      Shape13.addBox(0F, 0F, 0F, 1, 16, 1);
      Shape13.setRotationPoint(4F, 8F, -7F);
      Shape13.setTextureSize(154, 154);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 0, 0);
      Shape14.addBox(0F, 0F, 0F, 1, 16, 1);
      Shape14.setRotationPoint(6F, 8F, -5F);
      Shape14.setTextureSize(154, 154);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 0, 0);
      Shape15.addBox(0F, 0F, 0F, 1, 16, 1);
      Shape15.setRotationPoint(6F, 8F, 4F);
      Shape15.setTextureSize(154, 154);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);

      Shape16 = new ModelRenderer(this, 0, 0);
      Shape16.addBox(0F, 0F, 0F, 1, 16, 1);
      Shape16.setRotationPoint(4F, 8F, 6F);
      Shape16.setTextureSize(154, 154);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape16.mirror = false;
      Shape17 = new ModelRenderer(this, 0, 0);
      Shape17.addBox(0F, 0F, 0F, 1, 16, 1);
      Shape17.setRotationPoint(-5F, 8F, 6F);
      Shape17.setTextureSize(154, 154);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 0, 0);
      Shape18.addBox(-1F, 0F, 10F, 1, 16, 1);
      Shape18.setRotationPoint(-6F, 8F, -6F);
      Shape18.setTextureSize(154, 154);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Core.render(f5);
    Shape81.render(f5);
    Shape82.render(f5);
    Shape83.render(f5);
    Shape84.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
  }
  
  public void renderModel(float f){
	    Core.render(f);
	    Shape81.render(f);
	    Shape82.render(f);
	    Shape83.render(f);
	    Shape84.render(f);
	    Shape11.render(f);
	    Shape12.render(f);
	    Shape13.render(f);
	    Shape14.render(f);
	    Shape15.render(f);
	    Shape16.render(f);
	    Shape17.render(f);
	    Shape18.render(f);	  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
